import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'nextjs, react, blog'
}

export default function Layout ({ children } : { children: React.ReactNode }) { 
  return (
    <html lang="en">
      <body>{ children }</body>
    </html>
  )
}
